# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 14</font>

## Download: http://github.com/dsacademybr

## Web Scraping e Pandas

In [1]:
# Imports
import pandas as pd
import requests
from bs4 import BeautifulSoup 
from tabulate import tabulate

ModuleNotFoundError: No module named 'tabulate'

In [ ]:
# URL
res = requests.get("http://www.nationmaster.com/country-info/stats/Media/Internet-users")

In [ ]:
# Parser
soup = BeautifulSoup(res.content,'lxml')

In [ ]:
# Extrai a tabela do código HTML
table = soup.find_all('table')[0]

In [ ]:
print(table)

In [6]:
# Conversão da tabela HTML em um dataframe do Pandas
df = pd.read_html(str(table))

In [7]:
print(df)

[        #                                        COUNTRY         AMOUNT  DATE  \
0       1                                          China    389 million  2009
1       2                                  United States    245 million  2009
2       3                                          Japan  99.18 million  2009
3     NaN    Group of 7 countries (G7) average (profile)  80.32 million  2009
4       4                                         Brazil  75.98 million  2009
5       5                                        Germany  65.12 million  2010
6       6                                          India  61.34 million  2009
7       7                                         Russia   59.7 million  2010
8     NaN      Non-religious countries average (profile)  51.56 million  2009
9       8                                 United Kingdom  51.44 million  2009
10      9                                         France  44.63 million  2010
11     10                                        Nigeria  43.99 million  2009
12     11                                    South Korea   39.4 million  2009
13     12                                         Turkey     35 million  2010
14    NaN             Emerging markets average (profile)  32.99 million  2009
15     13                                         Mexico  31.02 million  2009
16     14                                          Italy  30.03 million  2010
17     15                                          Spain  29.09 million  2010
18     16                                         Canada  26.96 million  2009
19    NaN        East Asia and Pacific average (profile)  25.43 million  2009
20    NaN   High income OECD countries average (profile)  24.75 million  2009
21    NaN               Cold countries average (profile)  23.69 million  2009
22     17                                        Vietnam  23.38 million  2009
23     18                                       Colombia  22.54 million  2009
24     19                                         Poland  22.45 million  2010
25     20                                       Pakistan  20.43 million  2009
26     21                                          Egypt  20.14 million  2009
27     22                                      Indonesia     20 million  2009
28    NaN   Heavily indebted countries average (profile)  17.81 million  2009
29     23                                       Thailand  17.48 million  2009
..    ...                                            ...            ...   ...
219  =189                                         Monaco          23000  2010
220  =189                                  Liechtenstein          23000  2010
221  =189                                 Cayman Islands          23000  2008
222   192                       Central African Republic          22600  2009
223   193                                      Gibraltar          20200  2009
224   194                                        Liberia          20000  2009
225  =195                                        Vanuatu          17000  2009
226  =195                                     San Marino          17000  2010
227  =195                 Federated States of Micronesia          17000  2009
228  =195                          Saint Kitts and Nevis          17000  2009
229   199                                   Sierra Leone          14900  2009
230   200                              Equatorial Guinea          14400  2009
231   201                                Solomon Islands          10000  2009
232   202                                          Samoa           9000  2009
233   203                                          Tonga           8400  2009
234   204                                       Kiribati           7800  2009
235   205                                   Cook Islands           6000  2009
236   206                                         Tuvalu           4200  2008
237   207                         British Virgin Islands           4000  2002
238   208                                       Anguilla           3700  2009
239   209              Falkland Islands (Islas Malvinas)           2900  2009
240   210                               Marshall Islands           2200  2009
241   211                                     East Timor           2100  2009
242   212                              Wallis and Futuna           1300  2009
243   213                                     Montserrat           1200  2009
244   214                                           Niue           1100  2009
245  =215  Saint Helena, Ascension, and Tristan da Cunha            900  2009
246  =215                                   Saint Helena            900  2009
247   217                                        Tokelau            800  2008
248   218                               Christmas Island            464  2001

     GRAPH  HISTORY
0      NaN      NaN
1      NaN      NaN
2      NaN      NaN
3      NaN      NaN
4      NaN      NaN
5      NaN      NaN
6      NaN      NaN
7      NaN      NaN
8      NaN      NaN
9      NaN      NaN
10     NaN      NaN
11     NaN      NaN
12     NaN      NaN
13     NaN      NaN
14     NaN      NaN
15     NaN      NaN
16     NaN      NaN
17     NaN      NaN
18     NaN      NaN
19     NaN      NaN
20     NaN      NaN
21     NaN      NaN
22     NaN      NaN
23     NaN      NaN
24     NaN      NaN
25     NaN      NaN
26     NaN      NaN
27     NaN      NaN
28     NaN      NaN
29     NaN      NaN
..     ...      ...
219    NaN      NaN
220    NaN      NaN
221    NaN      NaN
222    NaN      NaN
223    NaN      NaN
224    NaN      NaN
225    NaN      NaN
226    NaN      NaN
227    NaN      NaN
228    NaN      NaN
229    NaN      NaN
230    NaN      NaN
231    NaN      NaN
232    NaN      NaN
233    NaN      NaN
234    NaN      NaN
235    NaN      NaN
236    NaN      NaN
237    NaN      NaN
238    NaN      NaN
239    NaN      NaN
240    NaN      NaN
241    NaN      NaN
242    NaN      NaN
243    NaN      NaN
244    NaN      NaN
245    NaN      NaN
246    NaN      NaN
247    NaN      NaN
248    NaN      NaN

[249 rows x 6 columns]]

In [8]:
# Conversão do dataframe para o formato JSON
print(df[0].to_json(orient='records'))

[{"#":"1","COUNTRY":"China","AMOUNT":"389 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"2","COUNTRY":"United States","AMOUNT":"245 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"3","COUNTRY":"Japan","AMOUNT":"99.18 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Group of 7 countries (G7) average (profile)","AMOUNT":"80.32 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"4","COUNTRY":"Brazil","AMOUNT":"75.98 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"5","COUNTRY":"Germany","AMOUNT":"65.12 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"6","COUNTRY":"India","AMOUNT":"61.34 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"7","COUNTRY":"Russia","AMOUNT":"59.7 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Non-religious countries average (profile)","AMOUNT":"51.56 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"8","COUNTRY":"United Kingdom","AMOUNT":"51.44 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"9","COUNTRY":"France","AMOUNT":"44.63 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"10","COUNTRY":"Nigeria","AMOUNT":"43.99 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"11","COUNTRY":"South Korea","AMOUNT":"39.4 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"12","COUNTRY":"Turkey","AMOUNT":"35 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Emerging markets average (profile)","AMOUNT":"32.99 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"13","COUNTRY":"Mexico","AMOUNT":"31.02 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"14","COUNTRY":"Italy","AMOUNT":"30.03 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"15","COUNTRY":"Spain","AMOUNT":"29.09 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"16","COUNTRY":"Canada","AMOUNT":"26.96 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"East Asia and Pacific average (profile)","AMOUNT":"25.43 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"High income OECD countries average (profile)","AMOUNT":"24.75 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Cold countries average (profile)","AMOUNT":"23.69 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"17","COUNTRY":"Vietnam","AMOUNT":"23.38 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"18","COUNTRY":"Colombia","AMOUNT":"22.54 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"19","COUNTRY":"Poland","AMOUNT":"22.45 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"20","COUNTRY":"Pakistan","AMOUNT":"20.43 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"21","COUNTRY":"Egypt","AMOUNT":"20.14 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"22","COUNTRY":"Indonesia","AMOUNT":"20 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Heavily indebted countries average (profile)","AMOUNT":"17.81 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"23","COUNTRY":"Thailand","AMOUNT":"17.48 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"South Asia average (profile)","AMOUNT":"16.69 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"24","COUNTRY":"Taiwan","AMOUNT":"16.15 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"25","COUNTRY":"Australia","AMOUNT":"15.81 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"26","COUNTRY":"Malaysia","AMOUNT":"15.36 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"27","COUNTRY":"Ukraine","AMOUNT":"15.3 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"28","COUNTRY":"Netherlands","AMOUNT":"14.87 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"29","COUNTRY":"Argentina","AMOUNT":"13.69 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Religious countries average (profile)","AMOUNT":"13.59 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"30","COUNTRY":"Morocco","AMOUNT":"13.21 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Eurozone average (profile)","AMOUNT":"12.48 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"NATO countries average (profile)","AMOUNT":"12.27 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"European Union average (profile)","AMOUNT":"10.69 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Former British colonies average (profile)","AMOUNT":"10.17 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"31","COUNTRY":"Saudi Arabia","AMOUNT":"9.77 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Europe average (profile)","AMOUNT":"9.61 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Catholic countries average (profile)","AMOUNT":"9.37 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"32","COUNTRY":"Peru","AMOUNT":"9.16 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"33","COUNTRY":"Venezuela","AMOUNT":"8.92 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Eastern Europe average (profile)","AMOUNT":"8.4 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"34","COUNTRY":"Sweden","AMOUNT":"8.4 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"35","COUNTRY":"Philippines","AMOUNT":"8.28 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Christian countries average (profile)","AMOUNT":"8.26 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"36","COUNTRY":"Iran","AMOUNT":"8.21 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"37","COUNTRY":"Belgium","AMOUNT":"8.11 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"38","COUNTRY":"Romania","AMOUNT":"7.79 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"South and Central Asia average (profile)","AMOUNT":"7.6 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"OPEC countries average (profile)","AMOUNT":"7.45 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"39","COUNTRY":"Chile","AMOUNT":"7.01 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"40","COUNTRY":"Czech Republic","AMOUNT":"6.68 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"41","COUNTRY":"Hungary","AMOUNT":"6.18 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"42","COUNTRY":"Austria","AMOUNT":"6.14 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Former Spanish colonies average (profile)","AMOUNT":"6.14 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"43","COUNTRY":"Switzerland","AMOUNT":"5.74 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Latin America and Caribbean average (profile)","AMOUNT":"5.71 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"failed states average (profile)","AMOUNT":"5.53 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"44","COUNTRY":"Kazakhstan","AMOUNT":"5.3 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"45","COUNTRY":"Portugal","AMOUNT":"5.17 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Potential Future EU Members average (profile)","AMOUNT":"5.1 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Muslim countries average (profile)","AMOUNT":"5.01 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"46","COUNTRY":"Greece","AMOUNT":"4.97 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Former Soviet republics average (profile)","AMOUNT":"4.93 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"47","COUNTRY":"Hong Kong","AMOUNT":"4.87 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"48","COUNTRY":"Denmark","AMOUNT":"4.75 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"49","COUNTRY":"Algeria","AMOUNT":"4.7 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"50","COUNTRY":"Uzbekistan","AMOUNT":"4.69 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Hot countries average (profile)","AMOUNT":"4.66 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"51","COUNTRY":"Israel","AMOUNT":"4.53 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Middle Eastern and North Africa average (profile)","AMOUNT":"4.51 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"52","COUNTRY":"Finland","AMOUNT":"4.48 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"53","COUNTRY":"Syria","AMOUNT":"4.47 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"54","COUNTRY":"Belarus","AMOUNT":"4.44 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"55","COUNTRY":"Norway","AMOUNT":"4.43 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"56","COUNTRY":"South Africa","AMOUNT":"4.42 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"57","COUNTRY":"Sudan","AMOUNT":"4.2 million","DATE":2008,"GRAPH":null,"HISTORY":null},{"#":"58","COUNTRY":"Serbia","AMOUNT":"4.11 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"59","COUNTRY":"Slovakia","AMOUNT":"4.06 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"60","COUNTRY":"Kenya","AMOUNT":"4 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"61","COUNTRY":"Azerbaijan","AMOUNT":"3.69 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"62","COUNTRY":"Tunisia","AMOUNT":"3.5 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"63","COUNTRY":"United Arab Emirates","AMOUNT":"3.45 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Tourist destinations average (profile)","AMOUNT":"3.42 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"64","COUNTRY":"New Zealand","AMOUNT":"3.4 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"65","COUNTRY":"Bulgaria","AMOUNT":"3.4 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"66","COUNTRY":"Ecuador","AMOUNT":"3.35 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"67","COUNTRY":"Singapore","AMOUNT":"3.23 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"68","COUNTRY":"Uganda","AMOUNT":"3.2 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"69","COUNTRY":"Ireland","AMOUNT":"3.04 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"70","COUNTRY":"Dominican Republic","AMOUNT":"2.7 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"71","COUNTRY":"Yemen","AMOUNT":"2.35 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Former French colonies average (profile)","AMOUNT":"2.31 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"72","COUNTRY":"Guatemala","AMOUNT":"2.28 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"73","COUNTRY":"Croatia","AMOUNT":"2.24 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"74","COUNTRY":"Kyrgyzstan","AMOUNT":"2.19 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"75","COUNTRY":"Lithuania","AMOUNT":"2.1 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"76","COUNTRY":"Senegal","AMOUNT":"1.82 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"77","COUNTRY":"Sri Lanka","AMOUNT":"1.78 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Landlocked countries average (profile)","AMOUNT":"1.64 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"78","COUNTRY":"Jordan","AMOUNT":"1.64 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":null,"COUNTRY":"Sub-Saharan Africa average (profile)","AMOUNT":"1.62 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"79","COUNTRY":"Cuba","AMOUNT":"1.61 million","DATE":2013,"GRAPH":null,"HISTORY":null},{"#":"80","COUNTRY":"Jamaica","AMOUNT":"1.58 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"81","COUNTRY":"Latvia","AMOUNT":"1.5 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"82","COUNTRY":"Costa Rica","AMOUNT":"1.49 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"83","COUNTRY":"Oman","AMOUNT":"1.47 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"84","COUNTRY":"Bosnia and Herzegovina","AMOUNT":"1.44 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"85","COUNTRY":"Zimbabwe","AMOUNT":"1.42 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"86","COUNTRY":"Uruguay","AMOUNT":"1.41 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=87","COUNTRY":"Gaza Strip","AMOUNT":"1.38 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=87","COUNTRY":"West Bank","AMOUNT":"1.38 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=89","COUNTRY":"Georgia","AMOUNT":"1.3 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"=89","COUNTRY":"Albania","AMOUNT":"1.3 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"91","COUNTRY":"Slovenia","AMOUNT":"1.3 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"92","COUNTRY":"Ghana","AMOUNT":"1.3 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"93","COUNTRY":"Moldova","AMOUNT":"1.29 million","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"94","COUNTRY":"Paraguay","AMOUNT":"1.1 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"95","COUNTRY":"Bolivia","AMOUNT":"1.1 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"96","COUNTRY":"Kuwait","AMOUNT":"1.1 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"97","COUNTRY":"Republic of Macedonia","AMOUNT":"1.06 million","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=98","COUNTRY":"Afghanistan","AMOUNT":"1000000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=98","COUNTRY":"Lebanon","AMOUNT":"1000000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=98","COUNTRY":"Puerto Rico","AMOUNT":"1000000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=98","COUNTRY":"Haiti","AMOUNT":"1000000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"102","COUNTRY":"Estonia","AMOUNT":"969700","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"103","COUNTRY":"Cote d'Ivoire","AMOUNT":"967300","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"104","COUNTRY":"Panama","AMOUNT":"959800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"105","COUNTRY":"Zambia","AMOUNT":"816200","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"106","COUNTRY":"Cameroon","AMOUNT":"749600","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"107","COUNTRY":"El Salvador","AMOUNT":"746000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"108","COUNTRY":"Honduras","AMOUNT":"731700","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"109","COUNTRY":"Malawi","AMOUNT":"716400","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"110","COUNTRY":"Tajikistan","AMOUNT":"700000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"111","COUNTRY":"Tanzania","AMOUNT":"678000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"112","COUNTRY":"Bangladesh","AMOUNT":"617300","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"113","COUNTRY":"Mozambique","AMOUNT":"613600","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"114","COUNTRY":"Angola","AMOUNT":"606700","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"115","COUNTRY":"Trinidad and Tobago","AMOUNT":"593000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"116","COUNTRY":"Nepal","AMOUNT":"577800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"117","COUNTRY":"Qatar","AMOUNT":"563800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"118","COUNTRY":"Rwanda","AMOUNT":"450000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"119","COUNTRY":"Ethiopia","AMOUNT":"447300","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"120","COUNTRY":"Cyprus","AMOUNT":"433800","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"121","COUNTRY":"Luxembourg","AMOUNT":"424500","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"122","COUNTRY":"Bahrain","AMOUNT":"419500","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"123","COUNTRY":"Togo","AMOUNT":"356300","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"124","COUNTRY":"Libya","AMOUNT":"353900","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"125","COUNTRY":"Mongolia","AMOUNT":"330000","DATE":2008,"GRAPH":null,"HISTORY":null},{"#":"126","COUNTRY":"Iraq","AMOUNT":"325900","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"127","COUNTRY":"Madagascar","AMOUNT":"319900","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"128","COUNTRY":"Brunei","AMOUNT":"314900","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"129","COUNTRY":"Iceland","AMOUNT":"301600","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"130","COUNTRY":"Laos","AMOUNT":"300000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=131","COUNTRY":"Mauritius","AMOUNT":"290000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=131","COUNTRY":"Democratic Republic of the Congo","AMOUNT":"290000","DATE":2008,"GRAPH":null,"HISTORY":null},{"#":"133","COUNTRY":"Montenegro","AMOUNT":"280000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"134","COUNTRY":"Macau","AMOUNT":"270200","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"135","COUNTRY":"Mali","AMOUNT":"249800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"136","COUNTRY":"Congo, Republic of the","AMOUNT":"245200","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"137","COUNTRY":"Malta","AMOUNT":"240600","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"138","COUNTRY":"Armenia","AMOUNT":"208200","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"139","COUNTRY":"Benin","AMOUNT":"200100","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"140","COUNTRY":"Eritrea","AMOUNT":"200000","DATE":2008,"GRAPH":null,"HISTORY":null},{"#":"141","COUNTRY":"Nicaragua","AMOUNT":"199800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"142","COUNTRY":"Guyana","AMOUNT":"189600","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"143","COUNTRY":"Barbados","AMOUNT":"188000","DATE":2008,"GRAPH":null,"HISTORY":null},{"#":"144","COUNTRY":"Burkina Faso","AMOUNT":"178100","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"145","COUNTRY":"Chad","AMOUNT":"168100","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"146","COUNTRY":"Suriname","AMOUNT":"163000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"147","COUNTRY":"Burundi","AMOUNT":"157800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"148","COUNTRY":"Cape Verde","AMOUNT":"150000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"149","COUNTRY":"Saint Lucia","AMOUNT":"142900","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"150","COUNTRY":"The Gambia","AMOUNT":"130100","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"151","COUNTRY":"Namibia","AMOUNT":"127500","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"152","COUNTRY":"Papua New Guinea","AMOUNT":"125000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=153","COUNTRY":"Botswana","AMOUNT":"120000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"=153","COUNTRY":"French Polynesia","AMOUNT":"120000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"155","COUNTRY":"Niger","AMOUNT":"115900","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"156","COUNTRY":"The Bahamas","AMOUNT":"115800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"157","COUNTRY":"Fiji","AMOUNT":"114200","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"158","COUNTRY":"Burma","AMOUNT":"110000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"159","COUNTRY":"Somalia","AMOUNT":"106000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"160","COUNTRY":"Gabon","AMOUNT":"98800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"161","COUNTRY":"Guinea","AMOUNT":"95000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"162","COUNTRY":"Swaziland","AMOUNT":"90100","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"163","COUNTRY":"Guam","AMOUNT":"90000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"164","COUNTRY":"Maldives","AMOUNT":"86400","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"165","COUNTRY":"New Caledonia","AMOUNT":"85000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"166","COUNTRY":"Turkmenistan","AMOUNT":"80400","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"167","COUNTRY":"Cambodia","AMOUNT":"78500","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"168","COUNTRY":"Lesotho","AMOUNT":"76800","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"169","COUNTRY":"Saint Vincent and the Grenadines","AMOUNT":"76000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"170","COUNTRY":"Mauritania","AMOUNT":"75000","DATE":2009,"GRAPH":null,"HISTORY":null},{"#":"171","COUNTRY":"Andorra","AMOUNT":"67200","DATE":2010,"GRAPH":null,"HISTORY":null},{"#":"172","COUNTRY":"Antigu

In [9]:
res = requests.get("http://www.nationmaster.com/country-info/stats/Media/Internet-users")
soup = BeautifulSoup(res.content,'lxml')
table = soup.find_all('table')[0] 
df = pd.read_html(str(table))
print( tabulate(df[0], headers='keys', tablefmt='psql') )

+-----+------+---------------------------------------------------+---------------+--------+---------+-----------+
|     | #    | COUNTRY                                           | AMOUNT        |   DATE |   GRAPH |   HISTORY |
|-----+------+---------------------------------------------------+---------------+--------+---------+-----------|
|   0 | 1    | China                                             | 389 million   |   2009 |     nan |       nan |
|   1 | 2    | United States                                     | 245 million   |   2009 |     nan |       nan |
|   2 | 3    | Japan                                             | 99.18 million |   2009 |     nan |       nan |
|   3 | nan  | Group of 7 countries (G7) average (profile)       | 80.32 million |   2009 |     nan |       nan |
|   4 | 4    | Brazil                                            | 75.98 million |   2009 |     nan |       nan |
|   5 | 5    | Germany                                           | 65.12 million |   2010 |     nan |       nan |
|   6 | 6    | India                                             | 61.34 million |   2009 |     nan |       nan |
|   7 | 7    | Russia                                            | 59.7 million  |   2010 |     nan |       nan |
|   8 | nan  | Non-religious countries average (profile)         | 51.56 million |   2009 |     nan |       nan |
|   9 | 8    | United Kingdom                                    | 51.44 million |   2009 |     nan |       nan |
|  10 | 9    | France                                            | 44.63 million |   2010 |     nan |       nan |
|  11 | 10   | Nigeria                                           | 43.99 million |   2009 |     nan |       nan |
|  12 | 11   | South Korea                                       | 39.4 million  |   2009 |     nan |       nan |
|  13 | 12   | Turkey                                            | 35 million    |   2010 |     nan |       nan |
|  14 | nan  | Emerging markets average (profile)                | 32.99 million |   2009 |     nan |       nan |
|  15 | 13   | Mexico                                            | 31.02 million |   2009 |     nan |       nan |
|  16 | 14   | Italy                                             | 30.03 million |   2010 |     nan |       nan |
|  17 | 15   | Spain                                             | 29.09 million |   2010 |     nan |       nan |
|  18 | 16   | Canada                                            | 26.96 million |   2009 |     nan |       nan |
|  19 | nan  | East Asia and Pacific average (profile)           | 25.43 million |   2009 |     nan |       nan |
|  20 | nan  | High income OECD countries average (profile)      | 24.75 million |   2009 |     nan |       nan |
|  21 | nan  | Cold countries average (profile)                  | 23.69 million |   2009 |     nan |       nan |
|  22 | 17   | Vietnam                                           | 23.38 million |   2009 |     nan |       nan |
|  23 | 18   | Colombia                                          | 22.54 million |   2009 |     nan |       nan |
|  24 | 19   | Poland                                            | 22.45 million |   2010 |     nan |       nan |
|  25 | 20   | Pakistan                                          | 20.43 million |   2009 |     nan |       nan |
|  26 | 21   | Egypt                                             | 20.14 million |   2009 |     nan |       nan |
|  27 | 22   | Indonesia                                         | 20 million    |   2009 |     nan |       nan |
|  28 | nan  | Heavily indebted countries average (profile)      | 17.81 million |   2009 |     nan |       nan |
|  29 | 23   | Thailand                                          | 17.48 million |   2009 |     nan |       nan |
|  30 | nan  | South Asia average (profile)                      | 16.69 million |   2009 |     nan |       nan |
|  31 | 24   | Taiwan                                            | 16.15 million |   2009 |     nan |       nan |
|  32 | 25   | Australia                                         | 15.81 million |   2009 |     nan |       nan |
|  33 | 26   | Malaysia                                          | 15.36 million |   2009 |     nan |       nan |
|  34 | 27   | Ukraine                                           | 15.3 million  |   2010 |     nan |       nan |
|  35 | 28   | Netherlands                                       | 14.87 million |   2010 |     nan |       nan |
|  36 | 29   | Argentina                                         | 13.69 million |   2009 |     nan |       nan |
|  37 | nan  | Religious countries average (profile)             | 13.59 million |   2009 |     nan |       nan |
|  38 | 30   | Morocco                                           | 13.21 million |   2009 |     nan |       nan |
|  39 | nan  | Eurozone average (profile)                        | 12.48 million |   2010 |     nan |       nan |
|  40 | nan  | NATO countries average (profile)                  | 12.27 million |   2010 |     nan |       nan |
|  41 | nan  | European Union average (profile)                  | 10.69 million |   2010 |     nan |       nan |
|  42 | nan  | Former British colonies average (profile)         | 10.17 million |   2009 |     nan |       nan |
|  43 | 31   | Saudi Arabia                                      | 9.77 million  |   2009 |     nan |       nan |
|  44 | nan  | Europe average (profile)                          | 9.61 million  |   2010 |     nan |       nan |
|  45 | nan  | Catholic countries average (profile)              | 9.37 million  |   2009 |     nan |       nan |
|  46 | 32   | Peru                                              | 9.16 million  |   2009 |     nan |       nan |
|  47 | 33   | Venezuela                                         | 8.92 million  |   2009 |     nan |       nan |
|  48 | nan  | Eastern Europe average (profile)                  | 8.4 million   |   2010 |     nan |       nan |
|  49 | 34   | Sweden                                            | 8.4 million   |   2010 |     nan |       nan |
|  50 | 35   | Philippines                                       | 8.28 million  |   2009 |     nan |       nan |
|  51 | nan  | Christian countries average (profile)             | 8.26 million  |   2009 |     nan |       nan |
|  52 | 36   | Iran                                              | 8.21 million  |   2009 |     nan |       nan |
|  53 | 37   | Belgium                                           | 8.11 million  |   2010 |     nan |       nan |
|  54 | 38   | Romania                                           | 7.79 million  |   2010 |     nan |       nan |
|  55 | nan  | South and Central Asia average (profile)          | 7.6 million   |   2009 |     nan |       nan |
|  56 | nan  | OPEC countries average (profile)                  | 7.45 million  |   2009 |     nan |       nan |
|  57 | 39   | Chile                                             | 7.01 million  |   2009 |     nan |       nan |
|  58 | 40   | Czech Republic                                    | 6.68 million  |   2010 |     nan |       nan |
|  59 | 41   | Hungary                                           | 6.18 million  |   2010 |     nan |       nan |
|  60 | 42   | Austria                                           | 6.14 million  |   2010 |     nan |       nan |
|  61 | nan  | Former Spanish colonies average (profile)         | 6.14 million  |   2009 |     nan |       nan |
|  62 | 43   | Switzerland                                       | 5.74 million  |   2010 |     nan |       nan |
|  63 | nan  | Latin America and Caribbean average (profile)     | 5.71 million  |   2009 |     nan |       nan |
|  64 | nan  | failed states average (profile)                   | 5.53 million  |   2009 |     nan |       nan |
|  65 | 44   | Kazakhstan                                        | 5.3 million   |   2010 |     nan |       nan |
|  66 | 45   | Portugal                                          | 5.17 million  |   2010 |     nan |       nan |
|  67 | nan  | Potential Future EU Members average (profile)     | 5.1 million   |   2009 |     nan |       nan |
|  68 | nan  | Muslim countries average (profile)                | 5.01 million  |   2009 |     nan |       nan |
|  69 | 46   | Greece                                            | 4.97 million  |   2010 |     nan |       nan |
|  70 | nan  | Former Soviet republics average (profile)         | 4.93 million  |   2009 |     nan |       nan |
|  71 | 47   | Hong Kong                                         | 4.87 million  |   2009 |     nan |       nan |
|  72 | 48   | Denmark                                           | 4.75 million  |   2010 |     nan |       nan |
|  73 | 49   | Algeria                                           | 4.7 million   |   2009 |     nan |       nan |
|  74 | 50   | Uzbekistan                                        | 4.69 million  |   2009 |     nan |       nan |
|  75 | nan  | Hot countries average (profile)                   | 4.66 million  |   2009 |     nan |       nan |
|  76 | 51   | Israel                                            | 4.53 million  |   2009 |     nan |       nan |
|  77 | nan  | Middle Eastern and North Africa average (profile) | 4.51 million  |   2009 |     nan |       nan |
|  78 | 52   | Finland                                           | 4.48 million  |   2010 |     nan |       nan |
|  79 | 53   | Syria                                             | 4.47 million  |   2009 |     nan |       nan |
|  80 | 54   | Belarus                                           | 4.44 million  |   2010 |     nan |       nan |
|  81 | 55   | Norway                                            | 4.43 million  |   2010 |     nan |       nan |
|  82 | 56   | South Africa                                      | 4.42 million  |   2009 |     nan |       nan |
|  83 | 57   | Sudan                                             | 4.2 million   |   2008 |     nan |       nan |
|  84 | 58   | Serbia                                            | 4.11 million  |   2009 |     nan |       nan |
|  85 | 59   | Slovakia                                          | 4.06 million  |   2010 |     nan |       nan |
|  86 | 60   | Kenya                                             | 4 million     |   2009 |     nan |       nan |
|  87 | 61   | Azerbaijan                                        | 3.69 million  |   2010 |     nan |       nan |
|  88 | 62   | Tunisia                                           | 3.5 million   |   2009 |     nan |       nan |
|  89 | 63   | United Arab Emirates                              | 3.45 million  |   2009 |     nan |       nan |
|  90 | nan  | Tourist destinations average (profile)            | 3.42 million  |   2009 |     nan |       nan |
|  91 | 64   | New Zealand                                       | 3.4 million   |   2009 |     nan |       nan |
|  92 | 65   | Bulgaria                                          | 3.4 million   |   2010 |     nan |       nan |
|  93 | 66   | Ecuador                                           | 3.35 million  |   2009 |     nan |       nan |
|  94 | 67   | Singapore                                         | 3.23 million  |   2009 |     nan |       nan |
|  95 | 68   | Uganda                                            | 3.2 million   |   2009 |     nan |       nan |
|  96 | 69   | Ireland                                           | 3.04 million  |   2010 |     nan |       nan |
|  97 | 70   | Dominican Republic                                | 2.7 million   |   2009 |     nan |       nan |
|  98 | 71   | Yemen                                             | 2.35 million  |   2009 |     nan |       nan |
|  99 | nan  | Former French colonies average (profile)          | 2.31 million  |   2009 |     nan |       nan |
| 100 | 72   | Guatemala                                         | 2.28 million  |   2009 |     nan |       nan |
| 101 | 73   | Croatia                                           | 2.24 million  |   2010 |     nan |       nan |
| 102 | 74   | Kyrgyzstan                                        | 2.19 million  |   2009 |     nan |       nan |
| 103 | 75   | Lithuania                                         | 2.1 million   |   2010 |     nan |       nan |
| 104 | 76   | Senegal                                           | 1.82 million  |   2009 |     nan |       nan |
| 105 | 77   | Sri Lanka                                         | 1.78 million  |   2009 |     nan |       nan |
| 106 | nan  | Landlocked countries average (profile)            | 1.64 million  |   2009 |     nan |       nan |
| 107 | 78   | Jordan                                            | 1.64 million  |   2009 |     nan |       nan |
| 108 | nan  | Sub-Saharan Africa average (profile)              | 1.62 million  |   2009 |     nan |       nan |
| 109 | 79   | Cuba                                              | 1.61 million  |   2013 |     nan |       nan |
| 110 | 80   | Jamaica                                           | 1.58 million  |   2009 |     nan |       nan |
| 111 | 81   | Latvia                                            | 1.5 million   |   2010 |     nan |       nan |
| 112 | 82   | Costa Rica                                        | 1.49 million  |   2009 |     nan |       nan |
| 113 | 83   | Oman                                              | 1.47 million  |   2009 |     nan |       nan |
| 114 | 84   | Bosnia and Herzegovina                            | 1.44 million  |   2010 |     nan |       nan |
| 115 | 85   | Zimbabwe                                          | 1.42 million  |   2009 |     nan |       nan |
| 116 | 86   | Uruguay                                           | 1.41 million  |   2009 |     nan |       nan |
| 117 | =87  | Gaza Strip                                        | 1.38 million  |   2009 |     nan |       nan |
| 118 | =87  | West Bank                                         | 1.38 million  |   2009 |     nan |       nan |
| 119 | =89  | Georgia                                           | 1.3 million   |   2010 |     nan |       nan |
| 120 | =89  | Albania                                           | 1.3 million   |   2010 |     nan |       nan |
| 121 | 91   | Slovenia                                          | 1.3 million   |   2010 |     nan |       nan |
| 122 | 92   | Ghana                                             | 1.3 million   |   2009 |     nan |       nan |
| 123 | 93   | Moldova                                           | 1.29 million  |   2010 |     nan |       nan |
| 124 | 94   | Paraguay                                          | 1.1 million   |   2009 |     nan |       nan |
| 125 | 95   | Bolivia                                           | 1.1 million   |   2009 |     nan |       nan |
| 126 | 96   | Kuwait                                            | 1.1 million   |   2009 |     nan |       nan |
| 127 | 97   | Republic of Macedonia                             | 1.06 million  |   2009 |     nan |       nan |
| 128 | =98  | Afghanistan                                       | 1000000       |   2009 |     nan |       nan |
| 129 | =98  | Lebanon                                           | 1000000       |   2009 |     nan |       nan |
| 130 | =98  | Puerto Rico                                       | 1000000       |   2009 |     nan |       nan |
| 131 | =98  | Haiti                                             | 1000000       |   2009 |     nan |       nan |
| 132 | 102  | Estonia                                           | 969700        |   2010 |     nan |       nan |
| 133 | 103  | Cote d'Ivoire                                     | 967300        |   2009 |     nan |       nan |
| 134 | 104  | Panama                                            | 959800        |   2009 |     nan |       nan |
| 135 | 105  | Zambia                                            | 816200        |   2009 |     nan |       nan |
| 136 | 106  | Cameroon                                          | 749600        |   2009 |     nan |       nan |
| 137 | 107  | El Salvador                                       | 746000        |   2009 |     nan |       nan |
| 138 | 108  | Honduras                                          | 731700        |   2009 |     nan |       nan |
| 139 | 109  | Malawi                                            | 716400        |   2009 |     nan |       nan |
| 140 | 110  | Tajikistan                                        | 700000        |   2009 |     nan |       nan |
| 141 | 111  | Tanzania                                          | 678000        |   2009 |     nan |       nan |
| 142 | 112  | Bangladesh                                        | 617300        |   2009 |     nan |       nan |
| 143 | 113  | Mozambique                                        | 613600        |   2009 |     nan |       nan |
| 144 | 114  | Angola                                            | 606700        |   2009 |     nan |       nan |
| 145 | 115  | Trinidad and Tobago                               | 593000        |   2009 |     nan |       nan |
| 146 | 116  | Nepal                                             | 577800        |   2009 |     nan |       nan |
| 147 | 117  | Qatar                                             | 563800        |   2009 |     nan |       nan |
| 148 | 118  | Rwanda                                            | 450000        |   2009 |     nan |       nan |
| 149 | 119  | Ethiopia                                          | 447300        |   2009 |     nan |       nan |
| 150 | 120  | Cyprus                                            | 433800        |   2010 |     nan |       nan |
| 151 | 121  | Luxembourg                                        | 424500        |   2010 |     nan |       nan |
| 152 | 122  | Bahrain                                           | 419500        |   2009 |     nan |       nan |
| 153 | 123  | Togo                                              | 356300        |   2009 |     nan |       nan |
| 154 | 124  | Libya                                             | 353900        |   2009 |     nan |       nan |
| 155 | 125  | Mongolia                                          | 330000        |   2008 |     nan |       nan |
| 156 | 126  | Iraq                                              | 325900        |   2009 |     nan |       nan |
| 157 | 127  | Madagascar                                        | 319900        |   2009 |     nan |       nan |
| 158 | 128  | Brunei                                            | 314900        |   2009 |     nan |       nan |
| 159 | 129  | Iceland                                           | 301600        |   2010 |     nan |       nan |
| 160 | 130  | Laos                                              | 300000        |   2009 |     nan |       nan |
| 161 | =131 | Mauritius                                         | 290000        |   2009 |     nan |       nan |
| 162 | =131 | Democratic Republic of the Congo                  | 290000        |   2008 |     nan |       nan |
| 163 | 133  | Montenegro                                        | 280000        |   2009 |     nan |       nan |
| 164 | 134  | Macau                                             | 270200        |   2009 |     nan |       nan |
| 165 | 135  | Mali                                              | 249800        |   2009 |     nan |       nan |
| 166 | 136  | Congo, Republic of the                            | 245200        |   2009 |     nan |       nan |
| 167 | 137  | Malta                                             | 240600        |   2010 |     nan |       nan |
| 168 | 138  | Armenia                                           | 208200        |   2010 |     nan |       nan |
| 169 | 139  | Benin                                             | 200100        |   2009 |     nan |       nan |
| 170 | 140  | Eritrea                                           | 200000        |   2008 |     nan |       nan |
| 171 | 141  | Nicaragua                                         | 199800        |   2009 |     nan |       nan |

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>